---
title: |
  | Deconvolución de datos de melanoma con quantiseqr:
  | Datos bulk RNA-seq: TCGA_SKCM
subtitle: " "
author: "Elena Eyre Sánchez, PhD"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    fig_caption: true
    number_sections: true
  word_document:
    toc: true
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    self-contained: true
    theme: journal
    urlcolor: tomato
linkcolor: steelblue2
fontsize: 8 pt
#nocite: |
#bibliography: scholar1.bib
params:
  #path_dir: "/Users/elenaeyre/Desktop/ELENA_UOC/TMF"
  #data: benthic_macroinv.csv
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "##",
  highlight = TRUE,
  prompt = FALSE,
  results = "markup"
)
```

# Introducción y Objetivo

# Paquetes y datos

Repositorio GitHub de : <https://github.com/Danko-Lab/quantiseqr/blob/main/tutorial_deconvolution.pdf>

```{r, cache = TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning=FALSE)
#if (!requireNamespace("BiocManager", quietly = TRUE)) {
#  install.packages("BiocManager")
#}
#BiocManager::install("quantiseqr")
package_to_load <- c("readr", "dplyr", "ggplot2", "tidyr", "dplyr","RColorBrewer", 
                     "Biobase","quantiseqr", "gplots")
for (package in package_to_load) {
  require(package, character.only = T); packageVersion(package)
}
extra_to_load <- c("knitr","stringr", "stringi", "ggrepel","ggpubr", "ggbreak",
                   "reshape2","ggfortify","cowplot","GEOquery","Seurat",
                   "data.table","limma","biomaRt","SummarizedExperiment","tibble")
for (package in extra_to_load) {
  require(package, character.only = T); packageVersion(package)
}
rm(package_to_load, extra_to_load)
```

#Datos


#Deconvolución

```{r, cache = TRUE, warning=FALSE, message=FALSE}
setwd("~/Desktop/ELENA_UOC/TFM")

gex <- read_delim("Datasets/TCGA-SKCM.htseq_fpkm.tsv",  delim = "\t", 
                  escape_double = FALSE, trim_ws = TRUE)
bulk_metadata <- read_delim("Datasets/TCGA-SKCM.GDC_phenotype.tsv", delim = "\t", 
                       escape_double = FALSE, trim_ws = TRUE)
#os_data <- read_delim("Datasets/TCGA-SKCM.survival.tsv", delim = "\t", 
#                      escape_double = FALSE, trim_ws = TRUE)

# Debido a que los autores proporcionan los genes con la nomeclatura de ENSEMBL, lo convierto a símbolos para que se pueda asociar con los símbolos del scRNA-seq:
mart <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
genes <- gex$Ensembl_ID
G_list <- getBM(filters= "ensembl_gene_id_version", attributes= c("ensembl_gene_id_version","hgnc_symbol"),values=genes,mart= mart)

# Para usar los símbolos en lugar de nombres de ENSEMBL:
gex2 <- merge(gex,G_list,by.x="Ensembl_ID",by.y="ensembl_gene_id_version")
gex2<-gex2[,-1]
gex2 <- aggregate(gex2, by = list(c(gex2$hgnc_symbol)), mean) # Agrego los posibles duplicados calculando la media
gex2 <- gex2[,-c(ncol(gex2))]
rownames(gex2) <- gex2$Group.1 # Los nombres de genes únicos sin duplicados sirven para dar nombre a las líneas
Probes <- gex2$Group.1
gex2$Group.1 <- NULL # Elimino las columnas usadas para conseguir los nombres
bulk.mtx <- as.data.frame(gex2) # Los datos de expresión

# Convertir los datos de expresión del bulk RNA-seq a objeto ExpressionSet:
bulk.eset <- Biobase::ExpressionSet(assayData = as.matrix(as.data.frame(bulk.mtx)))
bulk.eset

ti_racle <- quantiseqr::run_quantiseq(
  expression_data = bulk.eset@assayData$exprs,
  signature_matrix = "TIL10",
  is_arraydata = FALSE,
  is_tumordata = TRUE,
  scale_mRNA = TRUE
)
quantiplot(ti_racle)

```

Encontramos las proporciones del bulk RNA-seq en el apartado ```ti_racle```, el qual puedo integrar en la metadata que ya tenía y almacenar en un archivo para posteriores análisis.

```{r, cache = TRUE, warning=FALSE, message=FALSE}
ref.based.estimates <- as.data.frame(ti_racle)
ref.based.estimates$submitter_id.samples <- rownames(ref.based.estimates)
ref.based.estimates <- inner_join(ref.based.estimates, bulk_metadata, by = "submitter_id.samples")
knitr::kable(head(ref.based.estimates[,1:7]), digits=2, caption = "Sección de las primeras muestras y columnas como ejemplo del resultado")
write.csv(ref.based.estimates,"./quantiseq_TCGA_SKCM.csv", row.names = FALSE)
```

